services:
  database:
    image: postgres
    container_name: book-shop-payment-service
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=payment-service
    #    command: postgres -p 5432
    ports:
      - 5432:5432